#!/bin/bash
# ESXi HTTP Boot Server Deployment Script for RHEL (Enhanced Version)
# Optimized for RHEL 9 and ESXi 8.x compatibility

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration variables
HTTP_ROOT="/var/www/html"
ESXI_ISO_PATH=""
TFTP_ROOT="/var/lib/tftpboot"
DHCP_CONF="/etc/dhcp/dhcpd.conf"
NETWORK_INTERFACE=""

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

detect_network_interface() {
    NETWORK_INTERFACE=$(ip route | grep default | awk '{print $5}' | head -1)
    log_info "Detected network interface: $NETWORK_INTERFACE"
}

get_network_info() {
    # 动态获取 IP、子网掩码和网络号，适配非 /24 的环境
    IP_ADDR=$(ip addr show "$NETWORK_INTERFACE" | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
    # 使用 ipcalc 提取真实的掩码和网段
    MASK_BITS=$(ip addr show "$NETWORK_INTERFACE" | grep "inet\b" | awk '{print $2}' | cut -d/ -f2)
    SUBNET=$(ipcalc -n "$IP_ADDR/$MASK_BITS" | grep Network | awk '{print $2}' | cut -d/ -f1)
    NETMASK=$(ipcalc -m "$IP_ADDR/$MASK_BITS" | grep Netmask | awk '{print $2}')
    ROUTER="$IP_ADDR"
}

prompt_for_iso() {
    echo "Please provide the path to ESXi ISO file:"
    read -p "ISO Path: " ESXI_ISO_PATH
    if [[ ! -f "$ESXI_ISO_PATH" ]]; then
        log_error "ISO file not found: $ESXI_ISO_PATH"
        exit 1
    fi
}

install_packages() {
    log_info "Installing required packages..."
    dnf install -y httpd tftp-server dhcp-server ipcalc policycoreutils-python-utils
}

configure_firewall() {
    log_info "Configuring firewall..."
    systemctl enable --now firewalld
    for svc in http tftp dhcp; do
        firewall-cmd --permanent --add-service=$svc
    done
    firewall-cmd --reload
}

configure_http() {
    log_info "Configuring HTTP server..."
    mkdir -p "$HTTP_ROOT/esxi"
    systemctl enable --now httpd
}

configure_tftp() {
    log_info "Configuring TFTP server (Native Systemd mode)..."
    mkdir -p "$TFTP_ROOT"
    # RHEL 9 推荐直接使用 tftp.socket
    systemctl enable --now tftp.socket
}

extract_esxi_files() {
    log_info "Extracting ESXi files from ISO..."
    MOUNT_POINT="/mnt/esxi_iso_$(date +%s)"
    mkdir -p "$MOUNT_POINT"
    mount -o loop,ro "$ESXI_ISO_PATH" "$MOUNT_POINT"
    cp -r "$MOUNT_POINT/"* "$HTTP_ROOT/esxi/"
    umount "$MOUNT_POINT"
    rmdir "$MOUNT_POINT"

    # --- 关键改进：解决 SELinux 导致的 403 错误 ---
    if [ -x "$(command -v restorecon)" ]; then
        log_info "Fixing SELinux contexts for HTTP directories..."
        restorecon -Rv "$HTTP_ROOT/esxi" >/dev/null
    fi
}

configure_boot_cfg() {
    log_info "Optimizing boot.cfg for HTTP Boot..."
    
    BOOT_CFG_PATH="$HTTP_ROOT/esxi/efi/boot/boot.cfg"
    [[ ! -f "$BOOT_CFG_PATH" ]] && BOOT_CFG_PATH="$HTTP_ROOT/esxi/boot.cfg"

    if [[ -f "$BOOT_CFG_PATH" ]]; then
        cp "$BOOT_CFG_PATH" "$BOOT_CFG_PATH.bak"
        
        # 1. 修正 prefix，确保末尾没有多余斜杠
        sed -i "s@^prefix=.*@prefix=http://$IP_ADDR/esxi@g" "$BOOT_CFG_PATH"
        
        # 2. 精准删除除 prefix 行以外的所有行首斜杠（解决 ESXi 路径拼接问题）
        # 这样就不会破坏 http:// 里的斜杠了
        sed -i '/^prefix=/! s@^/@@g' "$BOOT_CFG_PATH"
        sed -i '/^prefix=/! s@ /@ @g' "$BOOT_CFG_PATH"

        log_info "Fixed boot.cfg content:"
        grep "^prefix=" "$BOOT_CFG_PATH"
        grep "^kernel=" "$BOOT_CFG_PATH"
    else
        log_error "boot.cfg not found!"
    fi
}
configure_dhcp_for_http_boot() {
    log_info "Configuring DHCP server..."
    get_network_info
    
    # 确定引导文件位置
    REL_BOOT_FILE="efi/boot/bootx64.efi"
    [[ ! -f "$HTTP_ROOT/esxi/$REL_BOOT_FILE" ]] && REL_BOOT_FILE="bootx64.efi"
    
    BOOT_FILE_URL="http://$IP_ADDR/esxi/$REL_BOOT_FILE"

    # 备份原配置
    [[ -f "$DHCP_CONF" ]] && cp "$DHCP_CONF" "$DHCP_CONF.bak"

    cat > "$DHCP_CONF" <<EOF
# Generated by ESXi Deployment Script
default-lease-time 600;
max-lease-time 7200;
authoritative;

subnet $SUBNET netmask $NETMASK {
    range ${SUBNET%.*}.100 ${SUBNET%.*}.200;
    option routers $ROUTER;
    option domain-name-servers 8.8.8.8;
    
    # UEFI HTTP Boot 核心配置
    if option vendor-class-identifier = "HTTPClient" {
        option bootfile-name "$BOOT_FILE_URL";
    } else {
        # 传统的 PXE 兜底
        next-server $IP_ADDR;
        filename "$REL_BOOT_FILE";
    }
}
EOF
    systemctl restart dhcpd
    systemctl enable dhcpd
}

main() {
    check_root
    detect_network_interface
    get_network_info
    prompt_for_iso
    
    install_packages
    configure_firewall
    configure_http
    configure_tftp
    extract_esxi_files
    configure_boot_cfg
    
    read -p "Apply DHCP configuration? (y/n): " DO_DHCP
    [[ "$DO_DHCP" == "y" ]] && configure_dhcp_for_http_boot
    
    log_info "Deployment Complete!"
    log_info "Test URL: http://$IP_ADDR/esxi/efi/boot/boot.cfg"
}

main